# Generated by Django 6.0.6 on 2026-07-31 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disquera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('fecha_lanzamiento', models.DateField()),
                ('portada_url', models.URLField(blank=True, max_length=500, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('disquera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albumes', to='disquera.disquera')),
            ],
        ),
    ]
